version: "3.8"

services:
  db:
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    env_file: .env
  app:
    build: ./server/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_CONTAINER_PORT}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - db
    env_file:
      - .env
  client:
    build: ./client/
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}